name: main-workflow

on: push

jobs:
  main-workflow-job:
    runs-on: ubuntu-23.04

    steps: 
      - name: check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
